import { neon } from '@neondatabase/serverless';
import { readFileSync } from 'node:fs';
import nextEnv from '@next/env';
nextEnv.loadEnvConfig(process.cwd());
const connection=process.env.LIMBA_DATABASE_URL||process.env.DATABASE_URL;
if(!connection) throw new Error('Database connection is not configured');
const sql=neon(connection);
const migration=readFileSync('scripts/limba/migrations/001-progress.sql','utf8');
for(const statement of migration.split(';').map(s=>s.trim()).filter(Boolean)) await sql.query(statement);
console.log('Additive progress migration applied. Existing records preserved.');
